In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from categorical_pomap import CategoricalPomap
import polars as pl

In [3]:
example_df = pl.from_dict(
    {'cat1': ['a', 'a', 'b', 'b'],
     'cat2': ['c', 'd', 'c', 'd'],
     'cat3': ['e', 'e', 'e', 'f'],
     }
)

In [4]:
example_df

shape: (4, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ a    ┆ d    ┆ e    │
│ b    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘

In [5]:
pmap_cat1 = CategoricalPomap(column='cat1', labels=['a', 'b'])
pmap_cat2 = CategoricalPomap(column='cat2', labels=['c', 'd'])
pmap_cat3 = CategoricalPomap(column='cat3', labels=['e', 'f'])

In [6]:
pmap_prod_12 = pmap_cat1.product(pmap_cat2)

In [7]:
pmap_sum = pmap_cat3.sum(pmap_prod_12)

In [8]:
pmap_sum.name

"Categorical cat3: ['e', 'f'] + Categorical cat1: ['a', 'b'] x Categorical cat2: ['c', 'd']"

In [9]:
pmap_sum.view_labels()

shape: (6, 3)
┌──────┬──────┬──────┐
│ cat3 ┆ cat1 ┆ cat2 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ e    ┆ null ┆ null │
│ f    ┆ null ┆ null │
│ null ┆ a    ┆ c    │
│ null ┆ a    ┆ d    │
│ null ┆ b    ┆ c    │
│ null ┆ b    ┆ d    │
└──────┴──────┴──────┘

In [13]:
pmap_cat1.label_rows_as_train(
    example_df,
    label='a'
)

shape: (4, 4)
┌──────┬──────┬──────┬──────────┐
│ cat1 ┆ cat2 ┆ cat3 ┆ train(a) │
│ ---  ┆ ---  ┆ ---  ┆ ---      │
│ str  ┆ str  ┆ str  ┆ bool     │
╞══════╪══════╪══════╪══════════╡
│ a    ┆ c    ┆ e    ┆ true     │
│ a    ┆ d    ┆ e    ┆ true     │
│ b    ┆ c    ┆ e    ┆ false    │
│ b    ┆ d    ┆ f    ┆ false    │
└──────┴──────┴──────┴──────────┘

In [15]:
pmap_prod_12.label_rows_as_train(
    example_df,
    label={'cat1': 'a', 'cat2': 'c'}
)

NameError: name 'pmap_prod_1' is not defined

In [13]:
example_df

shape: (4, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ a    ┆ d    ┆ e    │
│ b    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘