In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from categorical_pomap import CategoricalPomap
from pomap.pomap import Pomap

In [3]:
import polars as pl

In [21]:
example_df = pl.from_dict(
    {'cat1': ['a', 'b'],
    'cat2': ['c', 'd',],
    'cat3': ['e', 'f']
    }
)

In [22]:
example_df

shape: (2, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘

In [23]:
pmap_cat1 = CategoricalPomap(column='cat1', labels=['a', 'b'])
pmap_cat2 = CategoricalPomap(column='cat2', labels=['c', 'd'])
pmap_cat3 = CategoricalPomap(column='cat3', labels=['e', 'f'])

In [24]:
pmap_prod_12 = pmap_cat1.product(pmap_cat2)

In [25]:
pmap_sum = pmap_cat3.sum(pmap_prod_12)

In [26]:
pmap_sum.name

"Categorical cat3: ['e', 'f'] + Categorical cat1: ['a', 'b'] x Categorical cat2: ['c', 'd']"

In [27]:
pmap_sum.labels

shape: (6, 3)
┌──────┬──────┬──────┐
│ cat3 ┆ cat1 ┆ cat2 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ e    ┆ null ┆ null │
│ f    ┆ null ┆ null │
│ null ┆ a    ┆ c    │
│ null ┆ a    ┆ d    │
│ null ┆ b    ┆ c    │
│ null ┆ b    ┆ d    │
└──────┴──────┴──────┘

In [32]:
pmap_prod_12._label_rows_as(example_df, {'cat1': 'a', 'cat2': 'b', 'cat3': None}, label_as='train')

shape: (2, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘