In [21]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [22]:
from categorical_pomap import CategoricalPomap
import polars as pl

In [23]:
example_df = pl.from_dict(
    {'cat1': ['a', 'a', 'b', 'b'],
     'cat2': ['c', 'd', 'c', 'd'],
     'cat3': ['e', 'e', 'e', 'f'],
     }
)

In [24]:
example_df

shape: (4, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ a    ┆ d    ┆ e    │
│ b    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘

In [25]:
pmap_cat1 = CategoricalPomap(column='cat1', labels=['a', 'b'])
pmap_cat2 = CategoricalPomap(column='cat2', labels=['c', 'd'])
pmap_cat3 = CategoricalPomap(column='cat3', labels=['e', 'f'])

In [26]:
pmap_prod_12 = pmap_cat1.product(pmap_cat2)

In [27]:
pmap_sum = pmap_cat3.sum(pmap_prod_12)

In [28]:
pmap_sum.name

"Categorical cat3: ['e', 'f'] + Categorical cat1: ['a', 'b'] x Categorical cat2: ['c', 'd']"

In [29]:
pmap_sum.view_labels()

shape: (6, 3)
┌──────┬──────┬──────┐
│ cat3 ┆ cat1 ┆ cat2 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ e    ┆ null ┆ null │
│ f    ┆ null ┆ null │
│ null ┆ a    ┆ c    │
│ null ┆ a    ┆ d    │
│ null ┆ b    ┆ c    │
│ null ┆ b    ┆ d    │
└──────┴──────┴──────┘

In [30]:
pmap_prod_12.label_rows_as_train(
    example_df,
    label={'cat1': 'a', }
)

ValueError: can only call `.item()` if the dataframe is of shape (1, 1), or if explicit row/col values are provided; frame has shape (4, 3)

In [24]:
example_df

shape: (4, 2)
┌──────┬──────┐
│ cat1 ┆ cat2 │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ a    ┆ c    │
│ a    ┆ d    │
│ b    ┆ c    │
│ b    ┆ d    │
└──────┴──────┘