In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
from pomap.pomaps.categorical_pomap import CategoricalPomap
import polars as pl

In [14]:
example_df = pl.from_dict(
    {'cat1': ['a', 'a', 'b', 'b'],
     'cat2': ['c', 'd', 'c', 'd'],
     'cat3': ['e', 'e', 'e', 'f'],
     }
)

In [15]:
example_df

shape: (4, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ a    ┆ d    ┆ e    │
│ b    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘

In [16]:
pmap_cat1 = CategoricalPomap(column='cat1', labels=['a', 'b'])
pmap_cat2 = CategoricalPomap(column='cat2', labels=['c', 'd'])
pmap_cat3 = CategoricalPomap(column='cat3', labels=['e', 'f'])

In [17]:
pmap_prod_12 = pmap_cat1.product(pmap_cat2)

In [18]:
pmap_sum = pmap_cat3.sum(pmap_prod_12)

In [19]:
pmap_sum.name

"Categorical cat3: ['e', 'f'] + Categorical cat1: ['a', 'b'] x Categorical cat2: ['c', 'd']"

In [20]:
pmap_cat1.label_rows_as_train(
    example_df,
    label='a'
)

shape: (4, 4)
┌──────┬──────┬──────┬──────────┐
│ cat1 ┆ cat2 ┆ cat3 ┆ train(a) │
│ ---  ┆ ---  ┆ ---  ┆ ---      │
│ str  ┆ str  ┆ str  ┆ bool     │
╞══════╪══════╪══════╪══════════╡
│ a    ┆ c    ┆ e    ┆ true     │
│ a    ┆ d    ┆ e    ┆ true     │
│ b    ┆ c    ┆ e    ┆ false    │
│ b    ┆ d    ┆ f    ┆ false    │
└──────┴──────┴──────┴──────────┘

In [21]:
pmap_prod_12.label_rows_as_train(
    example_df,
    label={'cat1': 'a', 'cat2': 'c'}
)

shape: (4, 4)
┌──────┬──────┬──────┬─────────────────────────────────┐
│ cat1 ┆ cat2 ┆ cat3 ┆ train({'cat1': 'a', 'cat2': 'c… │
│ ---  ┆ ---  ┆ ---  ┆ ---                             │
│ str  ┆ str  ┆ str  ┆ bool                            │
╞══════╪══════╪══════╪═════════════════════════════════╡
│ a    ┆ c    ┆ e    ┆ false                           │
│ a    ┆ d    ┆ e    ┆ false                           │
│ b    ┆ c    ┆ e    ┆ false                           │
│ b    ┆ d    ┆ f    ┆ false                           │
└──────┴──────┴──────┴─────────────────────────────────┘

In [22]:
example_df

shape: (4, 3)
┌──────┬──────┬──────┐
│ cat1 ┆ cat2 ┆ cat3 │
│ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╡
│ a    ┆ c    ┆ e    │
│ a    ┆ d    ┆ e    │
│ b    ┆ c    ┆ e    │
│ b    ┆ d    ┆ f    │
└──────┴──────┴──────┘

In [27]:
# Investigate labels
pmap_sum.view_labels()

shape: (6, 3)
┌──────────────────────────────┬──────────────────────────────┬──────────────────────────────┐
│ Categorical cat1: ['a', 'b'] ┆ Categorical cat2: ['c', 'd'] ┆ Categorical cat3: ['e', 'f'] │
│ ---                          ┆ ---                          ┆ ---                          │
│ str                          ┆ str                          ┆ str                          │
╞══════════════════════════════╪══════════════════════════════╪══════════════════════════════╡
│ null                         ┆ null                         ┆ e                            │
│ null                         ┆ null                         ┆ f                            │
│ a                            ┆ c                            ┆ null                         │
│ a                            ┆ d                            ┆ null                         │
│ b                            ┆ c                            ┆ null                         │
│ b                            ┆ d                            ┆ null                         │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘